photobooth-backend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-backend
    tag: 5aed9c88ec6320284981c0e99cf1831a79feadc1
  network:
    http:
      servicePort: 8090
      ingress:
        path: /api
        host: photobooth-test.apps.okd.baloise.dev

photobooth-frontend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-frontend
    tag: 5aed9c88ec6320284981c0e99cf1831a79feadc1
  network:
    http:
      servicePort: 8080
      ingress:
        path: /
        host: photobooth-test.apps.okd.baloise.dev
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-dir
        - mountPath: /var/cache/nginx/client_temp
          name: nginx-empty
        - mountPath: /var/run/
          name: nginx-run
