photobooth-backend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-backend
    tag: 60287abfebb52b2e25476c65c5f9518768fc1597
  network:
    http:
      servicePort: 8090
      ingress:
        path: /api
        host: photobooth-test.apps.okd.baloise.dev

photobooth-frontend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-frontend
    tag: 54cf2ec03db05302431192894d2c70306c5cb4ef
  network:
    http:
      servicePort: 8080
      ingress:
        path: /
        host: photobooth-test.apps.okd.baloise.dev
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-dir
        - mountPath: /var/cache/nginx/client_temp
          name: nginx-empty
        - mountPath: /var/run/
          name: nginx-run
