photobooth-backend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-backend
    tag: 62e8b9c8412cd78ff7fab0b4ed89cc0d6d7ed539
  network:
    http:
      servicePort: 8080
      ingress:
        path: /
        host: photobooth-test.apps.okd.baloise.dev
  env:
    - name: TEST
      value: "this is just a test"

photobooth-frontend:
  replicaCount: 1
  image:
    repository: markovski/photobooth-frontend
    tag: 62e8b9c8412cd78ff7fab0b4ed89cc0d6d7ed539
  network:
    http:
      servicePort: 8080
      ingress:
        path: /
        host: photobooth-test.apps.okd.baloise.dev
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-dir
        - mountPath: /var/cache/nginx/client_temp
          name: nginx-empty
        - mountPath: /var/run/
          name: nginx-run
